export const activeUsersData = [
  {
    userId: 'USR1001',
    interests: ['Business', 'Travel'],
    rating: 4.5,
    chatRequestCount: 2,
    isReported: false,
  },
  {
    userId: 'USR1002',
    interests: ['Networking', 'Technology'],
    rating: 4.2,
    chatRequestCount: 5,
    isReported: true,
  },
  {
    userId: 'USR1003',
    interests: ['Books', 'Spirituality'],
    rating: 3.9,
    chatRequestCount: 1,
    isReported: false,
  },
  {
    userId: 'USR1004',
    interests: ['Food', 'Travel', 'Startups'],
    rating: 4.8,
    chatRequestCount: 3,
    isReported: false,
  },
  {
    userId: 'USR1005',
    interests: ['Photography', 'Adventure'],
    rating: 4.0,
    chatRequestCount: 0,
    isReported: false,
  },
  {
    userId: 'USR1006',
    interests: ['Fitness', 'Lifestyle'],
    rating: 3.5,
    chatRequestCount: 4,
    isReported: true,
  },
  {
    userId: 'USR1007',
    interests: ['Music', 'Tech Meetups'],
    rating: 4.6,
    chatRequestCount: 6,
    isReported: false,
  },
  {
    userId: 'USR1008',
    interests: ['Writing', 'Networking'],
    rating: 4.1,
    chatRequestCount: 2,
    isReported: false,
  },
  {
    userId: 'USR1009',
    interests: ['Health', 'Startups', 'Investing'],
    rating: 4.9,
    chatRequestCount: 8,
    isReported: false,
  },
  {
    userId: 'USR1010',
    interests: ['Design', 'Tech', 'Movies'],
    rating: 3.8,
    chatRequestCount: 1,
    isReported: false,
  },
];
