export const tripsData = [
  {
    id: '1',
    date: '10 June 2025',
    time: '06:30 AM',
    mode: 'flight',
    transportNumber: 'AI-101',
    from: 'Delhi',
    to: 'Mumbai',
  },
  {
    id: '2',
    date: '11 June 2025',
    time: '09:15 PM',
    mode: 'train',
    transportNumber: '12345 Shatabdi',
    from: 'Lucknow',
    to: 'Delhi',
  },
  {
    id: '3',
    date: '12 June 2025',
    time: '05:45 AM',
    mode: 'flight',
    transportNumber: '6E-302',
    from: 'Bangalore',
    to: 'Chennai',
  },
  {
    id: '4',
    date: '13 June 2025',
    time: '11:00 AM',
    mode: 'train',
    transportNumber: '22951 Rajdhani',
    from: 'Ahmedabad',
    to: 'New Delhi',
  },
  {
    id: '5',
    date: '14 June 2025',
    time: '01:15 PM',
    mode: 'flight',
    transportNumber: 'UK-705',
    from: 'Pune',
    to: 'Hyderabad',
  },
  {
    id: '6',
    date: '15 June 2025',
    time: '08:00 AM',
    mode: 'train',
    transportNumber: '12723 Telangana Express',
    from: 'Secunderabad',
    to: 'New Delhi',
  },
  {
    id: '7',
    date: '16 June 2025',
    time: '04:20 PM',
    mode: 'flight',
    transportNumber: 'AI-888',
    from: 'Mumbai',
    to: 'Goa',
  },
  {
    id: '8',
    date: '17 June 2025',
    time: '07:45 AM',
    mode: 'train',
    transportNumber: '12450 Goa Express',
    from: 'Goa',
    to: 'Delhi',
  },
  {
    id: '9',
    date: '18 June 2025',
    time: '02:30 PM',
    mode: 'flight',
    transportNumber: 'SG-456',
    from: 'Delhi',
    to: 'Kolkata',
  },
  {
    id: '10',
    date: '19 June 2025',
    time: '10:00 AM',
    mode: 'train',
    transportNumber: '12001 Kalka Shatabdi',
    from: 'New Delhi',
    to: 'Kalka',
  },
  {
    id: '11',
    date: '20 June 2025',
    time: '06:00 PM',
    mode: 'flight',
    transportNumber: 'AI-222',
    from: 'Chennai',
    to: 'Delhi',
  },
  {
    id: '12',
    date: '21 June 2025',
    time: '03:45 AM',
    mode: 'train',
    transportNumber: '12801 Purushottam Exp',
    from: 'Puri',
    to: 'New Delhi',
  },
  {
    id: '13',
    date: '22 June 2025',
    time: '11:30 AM',
    mode: 'flight',
    transportNumber: '6E-789',
    from: 'Jaipur',
    to: 'Delhi',
  },
  {
    id: '14',
    date: '23 June 2025',
    time: '08:15 PM',
    mode: 'train',
    transportNumber: '12951 Mumbai Rajdhani',
    from: 'Mumbai',
    to: 'Delhi',
  },
  {
    id: '15',
    date: '24 June 2025',
    time: '01:00 PM',
    mode: 'flight',
    transportNumber: 'AI-404',
    from: 'Delhi',
    to: 'Bangalore',
  },
  {
    id: '16',
    date: '25 June 2025',
    time: '10:30 AM',
    mode: 'train',
    transportNumber: '12303 Poorva Express',
    from: 'Howrah',
    to: 'Delhi',
  },
  {
    id: '17',
    date: '26 June 2025',
    time: '09:00 AM',
    mode: 'flight',
    transportNumber: 'UK-909',
    from: 'Kolkata',
    to: 'Bangalore',
  },
  {
    id: '18',
    date: '27 June 2025',
    time: '05:15 PM',
    mode: 'train',
    transportNumber: '12625 Kerala Express',
    from: 'Trivandrum',
    to: 'New Delhi',
  },
  {
    id: '19',
    date: '28 June 2025',
    time: '07:30 AM',
    mode: 'flight',
    transportNumber: 'AI-123',
    from: 'Delhi',
    to: 'Varanasi',
  },
  {
    id: '20',
    date: '29 June 2025',
    time: '06:45 PM',
    mode: 'train',
    transportNumber: '14257 Kashi Vishwanath',
    from: 'Varanasi',
    to: 'New Delhi',
  },
];

export const chatIds = Array.from({length: 20}, (_, i) => ({
  id: `abc${900 + i}`,
}));

export const meetSetupData = [
  {id: 'meet1', meetId: 'abc923', location: 'Mumbai', time: '10:30 AM'},
  {id: 'meet2', meetId: 'xyz842', location: 'Delhi', time: '02:00 PM'},
  {id: 'meet3', meetId: 'lmn431', location: 'Bangalore', time: '05:15 PM'},
  {id: 'meet4', meetId: 'def745', location: 'Chennai', time: '11:45 AM'},
  {id: 'meet5', meetId: 'ghi128', location: 'Hyderabad', time: '03:30 PM'},
];
export const ActiveTripsData = [
  {
    id: '1',
    date: '2025-06-10',
    time: '10:00 AM',
    mode: 'Bus',
    transportNumber: 'B123',
    from: 'Delhi',
    to: 'Agra',
    matchingUsersCount: 5,
    chatRequestCount: 2,
  },
  // other trips...
];
